### PR TITLE
Added config.json to initialize the custom data

### PR DESCRIPTION
**Pull request by chamathpali**
Sample config,
{
  "title": "99XT Open Source",
  "org_name": "99X Technology",
  "git_org" : "99XT",
  "base_url": "http://opensource.99xtechnology.com/",
  "blog_url": "http://blog.99xtechnology.com/",
  "logo_url": "images/logo-white.png"
}

### CODE REVIEW

**Comment by chamathpali** [comment]
#39

**Comment by charithsoori** [comment]
I am thinking will the users get confused since we especially saying organization (org_name ,git_org) name ?

**Comment by chamathpali** [comment]
how about organization_name, and git_org_name ?

**Comment by chamathpali** [comment]
Updated.

**Comment by chamathpali** [comment]
Added a configuration guide with commented info in readme

**Comment by charithsoori** [comment]
should we give a clue on "org_name":  is not mandatory somewhere ?

**Comment by charithsoori** [comment]
should we give a clue on "org_name":  is not mandatory somewhere ?

**Comment by charithsoori** [comment]
should we give a clue on "org_name":  is not mandatory somewhere ?

**Comment by chamathpali** [comment]
but it is used to make up the header title in page :D

**Comment by chamathpali** [comment]
but it is used to make up the header title in page :D

**Comment by charithsoori** [comment]
Maybe should give two options to users and organizations ?

**Pull request merged**
