### PR TITLE
gh-3: Added an interface to list down activities of the repositories

### LINKED ISSUE #3: list down available issues in a interface

### PR DESCRIPTION
**Pull request by dinukadesilva**
@rehrumesh @charithsoori @chamathpali 

this closes #3 

image

### CODE REVIEW

**Comment by dinukadesilva** [comment]
@rehrumesh @chamathpali @charithsoori 
Here are few screenshots of the latest changes. Please review

image

image

**Comment by chamathpali** [comment]
@dinukadesilva Good work here 👍 . can you host a ghpage in your forked repo and send a url to see it live?

**Comment by dinukadesilva** [comment]
@chamathpali 
Here is a link to a demo of these changes
https://dinukadesilva.github.io/99xt.github.io/

This demo has both #3 and #107 fixes

**Comment by rehrumesh** [comment]
This is great. We might need some UX improvements, but this is safe to merge. Amazing work @dinukadesilva 🥇

**Comment by rehrumesh** [comment]
@dinukadesilva I think there are some changes which you haven't pushed. Please refer the following images .
image

image

**Comment by dinukadesilva** [comment]
@rehrumesh you are correct. As also I have mentioned in the comment. There is another pull request which is #108 fixing #107.

**Comment by rehrumesh** [comment]
Apologies. Didn't noticed #108 
Great Work Dinuka

**Pull request merged**
